name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Update-Release
          path: "app/build/outputs/apk/release/*.apk"
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Updater-Debug
          path: "app/build/outputs/apk/debug/*.apk"
